- hosts: all
  become: true
  tasks:
    - name: set KUBECONFIG environment variable
      shell: export KUBECONFIG=/home/ubuntu/.kube/config
      become: true

    - name: delete old deployment
      command: kubectl delete -f /home/ubuntu/Deployment.yml
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
      become: true

    - name: delete old service
      command: kubectl delete -f /home/ubuntu/Service.yml
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
      become: true

    - name: create new deployment
      command: kubectl apply -f /home/ubuntu/Deployment.yml
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
      become: true

    - name: create new service
      command: kubectl apply -f /home/ubuntu/Service.yml
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
      become: true
