- hosts: all
  become: true
  tasks:
    # Optional: Delete the old deployment and service if needed (uncomment if necessary)
    # - name: delete old deployment
    #   command: kubectl delete -f /home/ubuntu/Deployment.yml

    # - name: delete old service
    #   command: kubectl delete -f /home/ubuntu/Service.yml

    - name: Apply Kubernetes deployment from Deployment.yml
      command: kubectl apply -f /home/ubuntu/Deployment.yml
      environment:
        KUBECONFIG: "/home/ubuntu/.kube/config"

   - name: Apply Kubernetes deployment from Service.yml
      command: kubectl apply -f /home/ubuntu/Service.yml
      environment:
        KUBECONFIG: "/home/ubuntu/.kube/config"
